before_script:
  - cabal update
  - ./ci/install-linters.sh
test:alltests:
  image: zenhack/haskell-capnp-ci
  script:
      # Run the tests:
    - cabal new-build
    - cabal new-test
      # Linting:
    - ./hlint.sh
      # Run stylish-haskell, and fail if it changes anything:
    - ./format.sh
    - git diff --exit-code
