before_script:
  # Report the versions of varioius software, to make diagnosing problems
  # easier:
  - ghc --version
  - cabal --version
  - capnp --version
  - stylish-haskell --version
  - hlint --version
  # Update the hackage databse:
  - cabal update
test:alltests:
  image: zenhack/haskell-capnp-ci
  script:
    - cabal new-build
    - cabal new-test
      # Linting:
    - ./scripts/hlint.sh
      # Run stylish-haskell, and fail if it changes anything:
    - ./scripts/format.sh
    - git diff --exit-code
      # Regenerate the schema, and make sure they're in-sync
      # with what was committed:
    - ./scripts/regen.sh
    - git diff --exit-code
      # Regenerate our other generated modules, and make sure
      # they're in-sync.
    - runhaskell scripts/gen-basic-instances.hs
    - git diff --exit-code
