before_script:
  # Install capnproto
  - apt-get update -y
  - apt-get install -y capnproto=0.6.1-1
  # Install extra haskell tools:
  - apt-get install -y stylish-haskell hlint
  # Report the versions of varioius software, to make diagnosing problems
  # easier:
  - ghc --version
  - cabal --version
  - capnp --version
  - stylish-haskell --version
  - hlint --version
  # Update the hackage databse:
  - cabal update
test:ghc-8.2:
  image: haskell:8.2.2
  script: ./ci/run-ci.sh
